description: "This is a template configuration file for the QXMT framework."

global_settings:
  random_seed: &global_seed 42
  model_type: "vqe"

hamiltonian:
  module_name: "qxmt.hamiltonians.pennylane"
  implement_name: "MolecularHamiltonian"
  params:
    molname: "H4"
    basis_name: "STO-3G"
    bondlength: 1.1
    active_electrons: 4
    active_orbitals: 4

device:
  platform: "pennylane"
  device_name: "lightning.qubit"
  n_qubits: 10
  shots: null
  random_seed: *global_seed

ansatz:
  module_name: "qxmt.ansatze.pennylane"
  implement_name: "UCCSDAnsatz"
  params: null

model:
  name: "basic"
  diff_method: "adjoint"
  optimizer_settings:
    name: "scipy.BFGS"
    params:
      gradient_method: "autodiff" # Use PennyLane autodiff (default), set to "numerical" to use SciPy numerical gradients
  params:
    max_steps: 500
    tol: 1e-6
    init_params:
      type: "zeros"
    verbose: true


evaluation:
  default_metrics:
  - "final_cost"
  - "hf_energy"
  - "fci_energy"
  custom_metrics: []
