description: "This is a template configuration file for the QXMT framework."

global_settings:
  random_seed: &global_seed 42
  model_type: "vqe"

hamiltonian:
  module_name: "qxmt.hamiltonians.pennylane"
  implement_name: "MolecularHamiltonian"
  params:
    symbols: ["Li", "H"]
    coordinates: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.74]]
    charge: 0
    multi: 1
    basis_name: "STO-3G"
    active_electrons: 2
    active_orbitals: 5
    reference_energy_methods: ["casci", "casscf", "fci"]
    max_cycle_macro: 50  # Only used for CASSCF
    conv_tol: 1e-7  # Only used for CASSCF
    orbital_optimization: true  # Only used for CASSCF
    unit: "angstrom"

device:
  platform: "pennylane"
  device_name: "lightning.qubit"
  n_qubits: 10
  shots: null
  random_seed: *global_seed

ansatz:
  module_name: "qxmt.ansatze.pennylane"
  implement_name: "UCCSDAnsatz"
  params: null

model:
  name: "basic"
  diff_method: "adjoint"
  optimizer_settings:
    name: "Adam"
    params:
      stepsize: 0.01
      beta1: 0.9
      beta2: 0.999
  params:
    max_steps: 500
    tol: 1e-6
    init_params:
      type: "zeros"
    verbose: true

evaluation:
  default_metrics:
  - "final_cost"
  - "hf_energy"
  - "casci_energy"
  - "casscf_energy"
  - "fci_energy"
  custom_metrics: []
