repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
-   repo: https://github.com/python/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3
      args:
        - --max-line-length=120
        - --extend-exclude=E203,E402,F841,F401,E302,E305
