dataset:
  type: "file"  # "file" or "generate"
  path: # full path or relative path from the root of the project
    data: "qxmt/data/mnist_784/images.npy"
    label: "qxmt/data/mnist_784/label.npy"
  random_seed: 42
  test_size: 0.2
  features: null
