description: "This is a template configuration file for the QXMT framework."

dataset:
  type: "file"  # "file" or "generate"
  path: # full path or relative path from the root of the project
    data: "qxmt/data/mnist_784/images.npy"
    label: "qxmt/data/mnist_784/label.npy"
  random_seed: 42
  test_size: 0.2
  features: null

device:
  platform: "pennylane"
  name: "default.qubit"
  n_qubits: 2
  # shots: 1000

model:
  model_name: "qsvm"
  model_file_name: "model.pkl"
  model_params:
    C: 1.0
    gamma: 0.05
  feature_map: "ZZFeatureMap"
  map_params:
    reps: 2
  kernel: "fidelity"

evaluation:
  default_metrics: ["accuracy", "precision", "recall", "f1_score"]
