description: "This is a template configuration file for the QXMT framework."

global_settings:
  random_seed: &global_seed 42
  task_type: "regression"

dataset:
  generate:
    generate_method: "linear"
    params: {
      "n_samples": 1000,
      "n_features": 2,
    }
  random_seed: *global_seed
  split:
    train_ratio: 0.8
    validation_ratio: 0.0
    test_ratio: 0.2
    shuffle: true
  features: null
  raw_preprocess_logic:
  - module_name: "qxmt.datasets.raw_preprocess.filter"
    implement_name: "filter_by_categorical"
    params:
      drop_na: true
  - module_name: "qxmt.datasets.raw_preprocess.sampling"
    implement_name: "sampling_by_num"
    params:
      n_samples: 100
      random_seed: *global_seed
  transform_logic:
      module_name: "qxmt.datasets.transform.normalization"
      implement_name: "normalization"

device:
  platform: "pennylane"
  device_name: "default.qubit"
  n_qubits: 2
  shots: 1024

feature_map:
  module_name: "qxmt.feature_maps.pennylane"
  implement_name: "ZZFeatureMap"
  params:
    reps: 2

kernel:
  module_name: "qxmt.kernels.pennylane"
  implement_name: "FidelityKernel"
  params: {}

model:
  name: "qsvr"
  params:
    C: 1.0
    gamma: "scale"

evaluation:
  default_metrics:
  - "mean_absolute_error"
  - "root_mean_squared_error"
  - "r2_score"
  custom_metrics: []
