description: "This is a template configuration file for the QXMT framework."

dataset:
  type: "file"  # "file" or "generate"
  path: # full path or relative path from the root of the project
    data: "data/mnist_784/images.npy"
    label: "data/mnist_784/label.npy"
  random_seed: 42
  test_size: 0.2
  features: null
  raw_preprocess_logic:
      module_name: "qxmt.datasets.raw_preprocess.sampling"
      implement_name: "sampling_by_each_class"
      params:
        n_samples: 100
  transform_logic:
    module_name: "qxmt.datasets.transform.reduction_by_pca"
    implement_name: "dimension_reduction_by_pca"
    params:
      n_components: 2

device:
  platform: "pennylane"
  name: "default.qubit"
  n_qubits: 2
  shots: null

model:
  name: "qsvm"
  file_name: "model.pkl"
  params:
    C: 1.0
    gamma: 0.05

feature_map:
  module_name: "qxmt.feature_maps.pennylane"
  implement_name: "ZZFeatureMap"
  params:
    reps: 2

kernel:
  module_name: "qxmt.kernels.pennylane"
  implement_name: "FidelityKernel"
  params: {}

evaluation:
  default_metrics: ["accuracy", "precision", "recall", "f1_score"]
