description: "This is a template configuration file for the QXMT framework."

global_settings:
  random_seed: &global_seed 42
  task_type: "classification"

dataset:
  openml:
    name: "mnist_784"
    id: 554
    return_format: "numpy"
    save_path: "data/openml/mnist_784/dataset.npy"
  random_seed: *global_seed
  split:
    train_ratio: 0.8
    validation_ratio: 0.0
    test_ratio: 0.2
    shuffle: true
  features: null
  raw_preprocess_logic:
    module_name: "qxmt.datasets.raw_preprocess.sampling"
    implement_name: "sampling_by_each_class"
    params:
      n_samples: 100
      labels: [0, 1]
      random_seed: *global_seed
  transform_logic:
    module_name: "qxmt.datasets.transform.reduction_by_pca"
    implement_name: "dimension_reduction_by_pca"
    params:
      n_components: 2

device:
  platform: "pennylane"
  name: "default.qubit"
  n_qubits: 2
  shots: null

feature_map:
  module_name: "qxmt.feature_maps.pennylane"
  implement_name: "ZZFeatureMap"
  params:
    reps: 2

kernel:
  module_name: "qxmt.kernels.pennylane"
  implement_name: "ProjectedKernel"
  params:
    gamma: 1.0
    projection: "xyz_sum"

model:
  name: "qsvc"
  file_name: "model.pkl"
  params:
    C: 1.0
    gamma: "scale"

evaluation:
  default_metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1_score"
  custom_metrics: []
