name: Publish Python Package to PyPI

on:
  # push:
  #   tags:
  #     - "v*.*.*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/qxmt/

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install --no-dev

    - name: Debug Poetry Config
      run: poetry config --list

    - name: Debug OIDC Token
      run: |
        curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN" \
          https://upload.pypi.org/account/token/

    - name: Debug Environment Variables
      run: env

    - name: Build the package
      run: poetry build

    - name: Publish to PyPI using Trusted Publisher
      run: poetry publish
